name: Django unittest

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9, "3.10", 3.11]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run Tests
        env:
          DATABASE_URL: ${{vars.TEST_DATABASE_URL}}
          SECRET_KEY: ${{vars.TEST_SECRET_KEY}}
          WEB_HOST: ${{vars.TEST_WEB_HOST}}
          WEB_PORT: ${{vars.TEST_WEB_PORT}}
          DEBUG: ${{vars.TEST_DEBUG}}
          EMAIL_PASSWORD: ${{vars.TEST_EMAIL_PASSWORD}}
          CSRF_TRUSTED_ORIGINS: ${{vars.TEST_CSRF_TRUSTED_ORIGINS}}
        run: |
          cd backend
          coverage run -m pytest --reuse-db -v -s --junitxml=report.xml
